PMApp/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'users.views.start_page', name='start_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^notifications/', include('user_notifications.urls', namespace='user_notifications')),
    # Вход в систему
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    # Операция выхода из системы
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
# coding=utf-8
from django.conf.urls import url
from tasks import views

__author__ = 'Ildar'

urlpatterns = [
    # Посмотреть все таски данного проекта
    url(r'view/(?P<project_id>\d+)/$', views.view_project_tasks, name='view_project_tasks'),
    # Добавить новый таск в проект
    url(r'add/(?P<project_id>\d+)/$', views.add_task_to_project, name='add_task_to_project'),
    # Посмотреть все "короткие" (меньше 7 дней) таски проекта
    url(r'/short_tasks/(?P<project_id>\d+)/$', views.view_short_tasks, name='view_short_tasks'),
    # Посмотреть детали отдельного таска
    url(r'(?P<pk>\d+)/view/$', views.ViewTask.as_view(), name='view_task'),
    # Редактировать таск
    url(r'(?P<pk>\d+)/edit/$', views.EditTask.as_view(), name='edit_task'),
    # Закрыть таск
    url(r'(?P<task_id>\d+)/close_task/$', views.close_task, name='close_task'),
    # Удалить таск
    url(r'(?P<task_id>\d+)/delete/$', views.delete_task, name='delete_task'),
    # Добавить файл таску
    url(r'(?P<task_id>\d+)/add_file/$', views.add_file_to_task, name='add_file_to_task'),
    # Загрузить файл
    url(r'download_file/(?P<file_id>\d+)/$', views.download_file, name='download_file'),
    # Удалить файл таска
    url(r'files/(?P<file_id>\d+)/remove/$', views.remove_task_file, name='remove_task_file'),
]

users/urls.py
# coding=utf-8
from django.conf.urls import url
from users import views

__author__ = 'Ildar'

urlpatterns = [
    # Регистрация нового пользователя
    url('registration/$', views.RegistrationView.as_view(), name='registration'),

    # Профиль стороннего пользователя
    url('(?P<pk>\d+)/view_profile/$', views.ViewUserProfile.as_view(), name='view_profile'),

    # Профиль пользователя
    url('profile/$', views.ProfileView.as_view(), name='profile'),
]

tasks/models.py
# coding=utf-8
from datetime import date
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projects.models import Project

task_choices = (  # Приоритет выполнения таска
            ("CRIT", "Critical"),
            ("HIGH", "High"),
            ("MED", "Medium"),
            ("LOW", "Low"),
            ("NONE", "None"),)


class Task(models.Model):
    """
    Таск в проекте
    """
    project = models.ForeignKey(Project)
    supertask = models.ForeignKey("self", null=True, blank=True)  # Главный таск. Этот таск является его подтаском.
    name = models.CharField(max_length=150)
    description = models.TextField(max_length=1000, blank=True)
    responsible_people = models.ManyToManyField(User)
    work_start = models.DateField(null=True, blank=True)  # Дата начала работы над таском
    work_end = models.DateField(null=True, blank=True)  # Дата окончания работы над таском
    priority = models.CharField(max_length=10, choices=task_choices)
    is_closed = models.BooleanField(default=False)

    @property
    def is_outdated(self):
        return (not self.is_closed) and (date.today() > self.work_end)

    def __unicode__(self):
        return "#%d: %s" % (self.id, self.name)


class TaskFile(models.Model):
    """
    Файл таска
    """
    task = models.ForeignKey(Task)
    add_date = models.DateTimeField()  # Дата добавления
    person_added = models.ForeignKey(User)  # Кем добавлен
    comment = models.TextField(max_length=1000, blank=True)
    file = models.FileField(upload_to="task_files")

    def __unicode__(self):
        return "(task=%s, file=%s)" % (self.task, self.file)

tasks/forms.py
__author__ = 'Ildar'

tasks/views.py
from datetime import datetime
import os
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q, F
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, UpdateView
from projects.models import Project, ProjectParticipant, ProjectDashboardNotification
from tasks import models
from tasks.models import Task, TaskFile
from user_notifications.models import UserNotification


def add_notification(project, event_author, message):
    creation_time = timezone.now()
    notif = ProjectDashboardNotification.objects.create(project=project, text=message,
                                                        event_date=creation_time, event_author=event_author)
    for teammate in project.team.all():
        UserNotification.objects.create(notification=notif, user=teammate, is_read=False)


class LoggedInMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


def exists_participant_admin(project, user):
    """ Check if the user is an administrator of this project"""
    return ProjectParticipant.objects.filter(project=project, participant=user, role='ADMIN').exists()


def exists_participant(project, user):
    """ Check if the user is a participant of this project"""
    return ProjectParticipant.objects.filter(project=project, participant=user).exists()


@login_required()
def view_project_tasks(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if not exists_participant(project, request.user):
        raise Http404()

    # All tasks - show only primary tasks (that don't have supertasks);
    # Only administrators and tasks' responsible people can see closed tasks
    tasks = project.task_set.filter(supertask=None)
    isAdmin = exists_participant_admin(project, request.user)
    if not isAdmin:
        q1 = Q(is_closed=False)
        q2 = Q(is_closed=True)
        q3 = Q(responsible_people__in=[request.user])
        tasks = tasks.filter(q1 | q2 & q3).distinct()
    tasks = tasks.order_by('is_closed')

    # User's primary tasks
    my_tasks = tasks.filter(responsible_people__in=[request.user])

    # User's subtasks
    my_subtasks = project.task_set.filter(responsible_people__in=[request.user]).exclude(supertask=None)

    return render(request, 'tasks/view_project_tasks.html', {'project': project, 'tasks': tasks,
                                                             'my_tasks': my_tasks,
                                                             'my_subtasks': my_subtasks,
                                                             'isAdmin': isAdmin})


@login_required()
def add_task_to_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    # Check if user trying to add the task is this project's admin
    if not exists_participant_admin(project, request.user):
        return HttpResponseRedirect(reverse('projects:choose_project'))

    error_msg = None
    name = description = ''
    supertask_id = responsible_people = work_start = work_end = priority = None
    supertask = None
    if request.method == "POST":
        # Fields that can be null or empty
        if 'supertask' in request.POST and request.POST['supertask'] != '':
            supertask_id = request.POST['supertask']
        if 'description' in request.POST:
            description = request.POST['description']
        if 'work_start' in request.POST and request.POST['work_start'] != '':
            work_start = request.POST['work_start']
        if 'work_end' in request.POST and request.POST['work_end'] != '':
            work_end = request.POST['work_end']

        try:
            name = request.POST['name']
            responsible_people = request.POST.getlist('responsible_people')
            priority = request.POST['priority']
            if len(name) == 0 or len(responsible_people) == 0 or len(priority) == 0:
                raise KeyError
        except KeyError:
            error_msg = "Please fill all the required fields (name, responsible people, priority)."

        # Check if there's such a supertask if it was specified
        if error_msg is None and supertask_id is not None:
            try:
                supertask = Task.objects.get(id=supertask_id, project=project)
            except Task.DoesNotExist:
                error_msg = "The supertask doesn't exist."
        # Check if priority is in our list of priorities
        if error_msg is None:
            if not any(priority in choice for choice in models.task_choices):
                error_msg = "The priority is unknown."
        # Check if work_end is greater than work_start
        if error_msg is None and work_start is not None and work_end is not None:
            date_start = datetime.strptime(work_start, '%Y-%m-%d')
            date_end = datetime.strptime(work_end, '%Y-%m-%d')
            if date_start > date_end:
                error_msg = "Work start date can't be bigger than work end date."
        # Check if all people set as responsible exist and are part of this project's team
        if error_msg is None:
            responsible_people = [User.objects.get(username=username) for username in responsible_people]
            for person in responsible_people:
                if not ProjectParticipant.objects.filter(participant=person, project=project).exists():
                    error_msg = "Not all responsible people specified consist in this project's team."

        # Create new task
        if error_msg is None:
            task = Task.objects.create(supertask=supertask, name=name, description=description,
                                       project=project, work_start=work_start,
                                       work_end=work_end, priority=priority)
            add_notification(project, request.user, "Task #%d has been added to the project" % task.id)
            for teammate in responsible_people:
                task.responsible_people.add(teammate)
            return HttpResponseRedirect(reverse('tasks:view_project_tasks', args=(project_id,)))

    if supertask_id is not None:
        supertask_id = int(supertask_id)

    # Getting only primary tasks for choosing as a supertask
    tasks = project.task_set.filter(supertask=None, is_closed=False)

    return render(request, 'tasks/add_task_to_project.html',
                  {'project': project, 'tasks': tasks, 'priorities': models.task_choices,
                   'name': name, 'supertask': supertask_id, 'description': description,
                   'responsible_people': responsible_people, 'work_start': work_start,
                   'work_end': work_end, 'priority': priority, 'error_msg': error_msg})


class ViewTask(LoggedInMixin, DetailView):
    model = Task
    template_name = "tasks/view_task.html"
    context_object_name = "task"

    def dispatch(self, *args, **kwargs):
        task = self.get_object()
        # Check if the user trying to view the task is a member of this project's team
        if not exists_participant(task.project, self.request.user):
            raise Http404()
        # Restrict viewing closed tasks only to administrators and responsible people
        if task.is_closed:
            is_responsible = task.responsible_people.filter(username=self.request.user.username).exists()
            if not is_responsible and not exists_participant_admin(task.project, self.request.user):
                raise Http404()

        return super(ViewTask, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewTask, self).get_context_data(**kwargs)
        user = self.request.user
        task = self.get_object()
        # Set this value if this user is the administrator of this task's project
        context['isAdmin'] = exists_participant_admin(task.project, user)
        if 'error_msg' in self.request.session:
            context['error_msg'] = self.request.session['error_msg']
            del self.request.session['error_msg']
        context['project'] = task.project
        context['subtasks'] = task.task_set
        # If this is not an administrator, show only opened tasks
        if not exists_participant_admin(task.project, user):
            context['subtasks'] = context['subtasks'].filter(is_closed=False)
        context['subtasks'] = context['subtasks'].order_by('is_closed')
        context['isResponsible'] = task.responsible_people.filter(username=user.username).exists()
        return context


class EditTask(LoggedInMixin, UpdateView):
    model = Task
    fields = ['supertask', 'name', 'description', 'responsible_people',
              'work_start', 'work_end', 'priority', 'is_closed']
    template_name = "tasks/edit_task.html"

    def dispatch(self, *args, **kwargs):
        project = self.get_object().project
        if not exists_participant_admin(project, self.request.user):
            raise Http404()
        return super(EditTask, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('tasks:view_task', args=(self.kwargs['pk'],))

    def get_context_data(self, **kwargs):
        context = super(EditTask, self).get_context_data(**kwargs)
        context['project'] = self.get_object().project
        return context

    def form_valid(self, form):
        resp = super(EditTask, self).form_valid(form)
        add_notification(self.get_object().project, self.request.user,
                         "Task #%d has been modified." % self.get_object().id)
        return resp

    def get_form(self, form_class=None):

tasks/templates/tasks/add_task_to_project.html
{% extends 'project/layout.html' %}

{% block title %}Add task to project{% endblock %}

{% block content %}
    <h1>Add new task to project #{{ project.id }}: {{ project.name }}</h1>
    {% if error_msg %}
        <span class="fieldError">{{ error_msg }}</span>
    {% endif %}

    <form method="post" action="{% url 'tasks:add_task_to_project' project.id %}">
        {% csrf_token %}
        <fieldset>
            <legend>Task information</legend>

            <table>
                <tr>
                    <td><label for="supertask">Supertask:</label></td>
                    <td>
                        <select name="supertask" id="supertask">
                            <option value="">(No supertask)</option>
                            {% for task in tasks %}
                                {% if supertask == task.id %}
                                    <option value="{{ task.id }}" selected>
                                {% else %}
                                    <option value="{{ task.id }}">
                                {% endif %}
                                #{{ task.id }}: {{ task.name }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label for="name">Name:</label></td>
                    <td><input type="text" name="name" id="name" value="{{ name }}" required="required" /></td>
                </tr>
                <tr>
                    <td><label for="description">Description:</label></td>
                    <td><textarea name="description" id="description">{{ description }}</textarea></td>
                </tr>
                <tr>
                    <td><label for="work_start">Work start date:</label></td>
                    <td><input type="date" name="work_start" id="work_start" value="{{ work_start }}"></td>
                </tr>
                <tr>
                    <td><label for="work_end">Work end date:</label></td>
                    <td><input type="date" name="work_end" id="work_end" value="{{ work_end }}"></td>
                </tr>
                <tr>
                    <td><label for="priority">Priority:</label></td>
                    <td>
                        <select name="priority" id="priority">
                            {% for prio in priorities %}
                                {% if prio.0 == priority %}
                                    <option value="{{ prio.0 }}" selected>{{ prio.1 }}</option>
                                {% else %}
                                    <option value="{{ prio.0 }}">{{ prio.1 }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><label for="responsible_people">Responsible people:</label></td>
                    <td>
                        <select name="responsible_people" id="responsible_people" multiple="multiple"
                                required="required">
                            {% for teammate in project.team.all %}
                                {% if teammate.username in responsible_people %}
                                    <option value="{{ teammate.username }}" selected>
                                        {{ teammate.username }}
                                    </option>
                                {% else %}
                                    <option value="{{ teammate.username }}">{{ teammate.username }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </td>
                </tr>
            </table>

        </fieldset>
        <input type="submit" value="Add task" />
    </form>
{% endblock %}

tasks/templates/tasks/delete_task.html
{% extends 'project/layout.html' %}

{% block title %}Delete task{% endblock %}

{% block content %}
    <h2>Delete task #{{ task.id }}: {{ task.name }}</h2>
    <span>Are you sure you want to delete this task? All subtasks will also be deleted.</span>
    <form method="post" action="{% url 'tasks:delete_task' task.id %}">
        {% csrf_token %}
        <input type="submit" value="Yes, delete it."/>
    </form>
{% endblock %}

tasks/templates/tasks/edit_task.html
{% extends 'project/layout.html' %}

{% block title %}Edit task{% endblock %}

{% block content %}
    <h1>Edit task {{ task.name }}</h1>

    <form method="post" action="{% url 'tasks:edit_task' task.id %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Save changes" />
    </form>
{% endblock %}

tasks/templates/tasks/view_project_tasks.html
{% extends 'project/layout.html' %}

{% block title %}View project tasks{% endblock %}

{% block content %}
    <h1>View project tasks</h1>
    <a href="{% url 'tasks:view_short_tasks' project.id %}">View short tasks (less than a week)</a><br />
    {% if isAdmin %}
        <a href="{% url 'tasks:add_task_to_project' project.id %}">Create new task</a><br /><br />
    {% endif %}

    <script type="text/javascript">
        $(function() {
            $("#tabs").tabs();
        })
    </script>

    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">My tasks</a></li>
            <li><a href="#tabs-2">My subtasks</a></li>
            <li><a href="#tabs-3">All tasks</a></li>
        </ul>

        <div id="tabs-1">
            {% if my_tasks %}
            <table class="rwd-table">
                {% for task in my_tasks %}
                    <tr>
                        <td>#{{ task.id }}: {{ task.name }}</td>
                        <td>
                            {% if task.work_start %}
                                From <span class="date">{{ task.work_start|date }}</span>
                            {% endif %}
                            {% if task.work_end %}
                                Till <span class="date">{{ task.work_end|date }}</span>
                            {% endif %}
                        </td>
                        <td>Priority:
                    <span class="priority{{ task.get_priority_display }}">
                        {{ task.get_priority_display }}
                    </span>
                        </td>
                        <td class="boldBig">
                            {% if task.is_closed %}
                                {{ task.is_closed|yesno:"Closed,No" }}
                            {% endif %}
                        </td>
                        <td>
                            {{ task.task_set.count }} subtask{{ task.task_set.count|pluralize }}
                        </td>
                        <td><a href="{% url 'tasks:view_task' task.id %}">More info</a></td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <i>No primary tasks</i>
            {% endif %}
        </div>

        <div id="tabs-2">
            {% if my_subtasks %}
            <table class="rwd-table">
                {% for task in my_subtasks %}
                    <tr>
                        <td>#{{ task.id }}: {{ task.name }}</td>
                        <td>
                            {% if task.work_start %}
                                From <span class="date">{{ task.work_start|date }}</span>
                            {% endif %}
                            {% if task.work_end %}
                                Till <span class="date">{{ task.work_end|date }}</span>
                            {% endif %}
                        </td>
                        <td>Priority:
                            <span class="priority{{ task.get_priority_display }}">
                                {{ task.get_priority_display }}
                            </span>
                        </td>
                        <td class="boldBig">
                            {% if task.is_closed %}
                                {{ task.is_closed|yesno:"Closed,No" }}
                            {% endif %}
                        </td>
                        <td><a href="{% url 'tasks:view_task' task.id %}">More info</a></td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <i>No subtasks.</i>
            {% endif %}
        </div>

        <div id="tabs-3">
            <table class="rwd-table">
                {% for task in tasks %}
                    <tr>
                        <td>#{{ task.id }}: {{ task.name }}</td>
                        <td>
                            {% if task.work_start %}
                                From <span class="date">{{ task.work_start|date }}</span>
                            {% endif %}
                            {% if task.work_end %}
                                Till <span class="date">{{ task.work_end|date }}</span>
                            {% endif %}
                        </td>
                        <td>Priority:
                            <span class="priority{{ task.get_priority_display }}">
                                {{ task.get_priority_display }}
                            </span>
                        </td>
                        <td class="boldBig">
                            {% if task.is_closed %}
                                {{ task.is_closed|yesno:"Closed,No" }}
                            {% endif %}
                        </td>
                        <td>
                            {{ task.task_set.count }} subtask{{ task.task_set.count|pluralize }}
                        </td>
                        <td><a href="{% url 'tasks:view_task' task.id %}">More info</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock %}

tasks/templates/tasks/view_short_tasks.html
{% extends 'project/layout.html' %}

{% block title %}View project's short tasks{% endblock %}

{% block content %}
    <h1>View short tasks of project</h1>

    <table class="rwd-table">
        {% for task in tasks %}
            <tr>
                <td>#{{ task.id }}: {{ task.name }}</td>
                <td>
                    {% if task.work_start %}
                        From <span class="date">{{ task.work_start|date }}</span>
                    {% endif %}
                    {% if task.work_end %}
                        Till <span class="date">{{ task.work_end|date }}</span>
                    {% endif %}
                </td>
                <td>Priority:
                    <span class="priority{{ task.get_priority_display }}">
                        {{ task.get_priority_display }}
                    </span>
                </td>
                <td class="boldBig">
                    {% if task.is_closed %}
                        {{ task.is_closed|yesno:"Closed,No" }}
                    {% endif %}
                </td>
                <td>
                    {% if not task.supertask %}
                        {{ task.task_set.count }} subtask{{ task.task_set.count|pluralize }}
                    {% endif %}
                </td>
                <td><a href="{% url 'tasks:view_task' task.id %}">More info</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

tasks/templates/tasks/view_task.html
{% extends 'project/layout.html' %}

{% block title %}View task{% endblock %}

{% block content %}
    <h1>Task #{{ task.id }}: {{ task.name }}</h1>

    {% if error_msg %}
        <span class="fieldError">{{ error_msg }}</span><br />
    {% endif %}

    {% if isAdmin %}
        <a href="{% url 'tasks:delete_task' task.id %}">Delete task</a>
        <a href="{% url 'tasks:edit_task' task.id %}">Edit task</a><br /><br />

        <script type="text/javascript">
            function deleteFile(url) {
                var form = $("#deleteFileForm");
                form.prop('action', url);
                form.submit();
            }
        </script>
        <form method="post" id="deleteFileForm">
            {% csrf_token %}
        </form>
    {% endif %}

    <fieldset>
    <legend>Task information</legend>
    <table>
        {% if task.supertask %}
        <tr>
            <td>Supertask:</td>
            <td><a href="{% url 'tasks:view_task' task.supertask.id %}">
                #{{ task.supertask.id }}: {{ task.supertask.name }}</a></td>
        </tr>
        {% endif %}
        <tr>
            <td>Description:</td>
            <td>
                {% if task.description %}
                    {{ task.description }}
                {% else %}
                    <i>No description</i>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>Timing:</td>
            <td>
                {% if task.work_start %}
                    From <span class="date">{{ task.work_start|date }}</span>
                {% endif %}
                {% if task.work_end %}
                    Till <span class="date">{{ task.work_end|date }}</span>
                {% endif %}
                {% if task.work_end and task.is_outdated %}
                    <span class="outdated">(PAST DEADLINE)</span>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>Priority:</td>
            <td class="priority{{ task.get_priority_display }}">{{ task.get_priority_display }}</td>
        </tr>
        <tr>
            <td>Responsible people:</td>
            <td>
                <ul>
                    {% for person in task.responsible_people.all %}
                        <li><a href="{% url 'users:view_profile' person.id %}">{{ person }}</a></li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        {% if task.is_closed %}
            <tr class="boldBig">
                <td>Closed:</td>
                <td>{{ task.is_closed|yesno:"Closed,No" }}</td>
            </tr>
        {% endif %}
    </table>
    </fieldset>

    {% if isAdmin or isResponsible %}
        <form method="post" action="{% url 'tasks:close_task' task.id %}">
            {% csrf_token %}
            <br/>
            {% if task.is_closed %}
                <input type="hidden" name="close_task" value="0" />
                <input type="submit" value="Reopen task"/>
            {% else %}
                <input type="hidden" name="close_task" value="1" />
                <input type="submit" value="Close task"/>
            {% endif %}
        </form>
        <br/>
    {% endif %}

    {% if subtasks %}
        <h3>Subtasks</h3>
        <table class="rwd-table">
        {% for subtask in subtasks %}
            <tr>
                <td>#{{ subtask.id }}: {{ subtask.name }}</td>
                <td>
                    {% if subtask.work_start %}
                    From <span class="date">{{ subtask.work_start|date }}</span>
                    {% endif %}
                    {% if subtask.work_end %}
                    Till <span class="date">{{ subtask.work_end|date }}</span>
                    {% endif %}
                </td>
                <td>Priority:
                    <span class="priority{{ subtask.get_priority_display }}">
                        {{ subtask.get_priority_display }}
                    </span>
                </td>
                <td class="boldBig">
                {% if subtask.is_closed %}
                    {{ subtask.is_closed|yesno:"Closed,No" }}
                {% endif %}
                </td>
                <td><a href="{% url 'tasks:view_task' subtask.id %}">More info</a></td>
            </tr>
        {% endfor %}
        </table>
    {% elif not task.supertask %}
        <br />
        <i>No subtasks</i>
    {% endif %}

    {% if task.taskfile_set.all %}
    <h3>Task files</h3>
    <table class="rwd-table">
        {% for file in task.taskfile_set.all %}
            <tr>
                <td>{{ file.add_date|date }}</td>
                <td>Added by <a href="{% url 'users:view_profile' file.person_added.id %}">
                    {{ file.person_added.username }}</a></td>
                <td>Comment: {{ file.comment }}</td>
                <td><a href="{% url 'tasks:download_file' file.id %}">Download</a></td>
                {% if isAdmin %}
                <td><a href="javascript:deleteFile('{% url 'tasks:remove_task_file' file.id %}');">
                    Delete file</a></td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
    {% endif %}
    <br />

    <div id="fileAdd">
        <h3>Add file to task</h3>
        <form method="post" action="{% url 'tasks:add_file_to_task' task.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div style="margin-bottom: 10px;">
            <input type="hidden" name="task_id" value="{{ task.id }}">
            <input type="file" name="file" />
            </div>
            <div>
            <label for="comment">Comment</label>: <textarea name="comment"></textarea>
            <input type="submit" value="Upload" />
            </div>
        </form>
    </div>
{% endblock %}