PMApp/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'users.views.start_page', name='start_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^notifications/', include('user_notifications.urls', namespace='user_notifications')),
    # Вход в систему
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    # Операция выхода из системы
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
# coding=utf-8
from django.conf.urls import url
from projects import views

__author__ = 'Ildar'

urlpatterns = [
    # Главная страница проекта
    url(r'(?P<pk>\d+)/view/$', views.ViewProject.as_view(), name='view_project'),
    # Создать новый проект
    url(r'create/$', views.CreateProject.as_view(), name='create_project'),
    # Выбрать проект из списка для начала работы с ним
    url(r'choose/$', views.ChooseProject.as_view(), name='choose_project'),
    # Посмотреть команду проекта
    url(r'(?P<pk>\d+)/team/$', views.ProjectTeam.as_view(), name='project_team'),
    # Добавить нового сотрудника в команду проекта
    url(r'(?P<project_id>\d+)/add_person/$', views.AddPerson.as_view(), name='add_person'),
    # Вернуть юзернеймы пользователей, которые подходят под поисковую фразу
    url(r'(?P<project_id>\d+)/get_usernames/$', views.get_usernames, name='get_usernames'),
    # Удалить пользователя из проекта
    url(r'(?P<project_id>\d+)/team/delete/$', views.delete_person_from_project,
        name='delete_person_from_project'),
    # Сменить роль пользователя в проекте, роль может менять только админ проекта
    url(r'team/(?P<participant_id>\d+)/change_role/$', views.change_user_role,
        name='change_user_role'),
    # Сменить должность пользователя в проекте, должность может менять только админ проекта
    url(r'team/change_user_appointment/$', views.change_user_appointment, name='change_user_appointment'),
    # Удалить проект
    url(r'(?P<pk>\d+)/delete/$', views.DeleteProject.as_view(), name='delete_project'),
    # Добавить сообщение в чат
    url(r'(?P<project_id>\d+)/add_chat_message/$', views.add_chat_message, name='add_chat_message'),
    # Получить новые сообщения чата
    url(r'(?P<project_id>\d+)/get_chat_messages/$', views.get_chat_messages,
        name='get_chat_messages'),
    # Посмотреть промежуточные этапы данного проекта
    url(r'(?P<pk>\d+)/milestones/$', views.ViewMilestones.as_view(), name='view_milestones'),
    # Добавить новый промежуточный этап проекту
    url(r'(?P<pk>\d+)/add_milestone/$', views.AddMilestone.as_view(), name='add_milestone'),
    # Посмотреть отдельный промежуточный этап этого проекта
    url(r'milestones/(?P<pk>\d+)/view_milestone/$', views.ViewMilestone.as_view(), name='view_milestone'),
    # Редактировать промежуточный этап
    url(r'milestones/(?P<pk>\d+)/edit/$', views.EditMilestone.as_view(), name='edit_milestone'),
    # Удалить промежуточный этап
    url(r'milestones/(?P<milestone_id>\d+)/delete_milestone/$', views.delete_milestone, name='delete_milestone'),
    # Посмотреть ссылки, созданные для проекта
    url(r'(?P<pk>\d+)/links/view/$', views.ViewLinks.as_view(), name='view_links'),
    # Создать новую ссылку для проекта
    url(r'(?P<pk>\d+)/links/create_link/$', views.CreateLink.as_view(), name='create_link'),
    # Редактировать существующую ссылку
    url(r'links/(?P<pk>\d+)/edit_link/$', views.EditLink.as_view(), name='edit_link'),
    # Удалить ссылку
    url(r'links/delete_link/$', views.delete_link, name='delete_link'),

    # Статистика по сайту
    url(r'statistics/$', views.view_statistics, name='view_statistics'),
]

users/urls.py
# coding=utf-8
from django.conf.urls import url
from users import views

__author__ = 'Ildar'

urlpatterns = [
    # Регистрация нового пользователя
    url('registration/$', views.RegistrationView.as_view(), name='registration'),

    # Профиль стороннего пользователя
    url('(?P<pk>\d+)/view_profile/$', views.ViewUserProfile.as_view(), name='view_profile'),

    # Профиль пользователя
    url('profile/$', views.ProfileView.as_view(), name='profile'),
]

projects/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Project(models.Model):
    """ Проект
    """
    name = models.CharField(max_length=150)  # Название проекта
    description = models.TextField(max_length=1000, null=True, blank=True)  # Описание
    work_start = models.DateField()  # Дата начала работы над проектом
    work_deadline = models.DateField()  # Дата окончания работы над проектом

    team = models.ManyToManyField(User,
                                  through='ProjectParticipant')  # Команда, работающая над проектом - список юзеров

    def __unicode__(self):
        return "(id=%d, name=%s)" % (self.id, self.name)


class ProjectDashboardNotification(models.Model):
    """
    Уведомления о каком-либо действии с проектом на главной странице проекта
    """
    project = models.ForeignKey(Project)  # Проект, в котором произошло действие
    text = models.CharField(max_length=250)  # Текст уведомления
    event_date = models.DateTimeField()  # Дата, когда событие произошло
    event_author = models.ForeignKey(User)  # Кто совершил действие, отраженное в данном уведомлении

    def __unicode__(self):
        return "(project=%s, author=%s, date=%s)" % (
            self.project, self.event_author, self.event_date)


class ProjectChatMessage(models.Model):
    """
    Сообщение в чате проекта
    """
    project = models.ForeignKey(Project)
    author = models.ForeignKey(User)  # Автор сообщения
    text = models.CharField(max_length=200)  # Текст сообщения
    publish_date = models.DateTimeField()  # Дата публикации сообщения в чате

    def __unicode__(self):
        return "(project=%s, author=%s, text=(%s), publish_date=%s)" \
               % (self.project, self.author,
                  self.text if len(self.text.__str__()) < 50 else (self.text[:50] + "..."),
                  self.publish_date)


class ProjectLink(models.Model):
    """
    Ссылка на какой-то сторонний ресурс, связанный с проектом, например, исходный код приложения проекта
    """
    project = models.ForeignKey(Project)
    url = models.URLField()
    description = models.TextField()
    publisher = models.ForeignKey(User)  # Кто разместил ссылку
    publish_date = models.DateTimeField()  # Дата публикации ссылки

    def __unicode__(self):
        return "(project=%s, url=%s)" % (self.project, self.url)


class ProjectMilestone(models.Model):
    """
    Промежуточный этап разработки проекта
    """
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    due_date = models.DateField()  # К какому числу этап должен быть готов
    responsible_people = models.ManyToManyField(User)  # Кто ответственнен за достижение этапа

    def __unicode__(self):
        return "(project=%s, name=%s, due date=%s)" % (self.project, self.name, self.due_date)


role_choices = (  # Роль(привилегии) в проекте
             ("ADMIN", "Administrator"),
             ("USER", "Teammate"),
          )


class ProjectParticipant(models.Model):
    """
    Участник проекта
    """
    project = models.ForeignKey(Project)
    participant = models.ForeignKey(User)
    appointment = models.CharField(max_length=100)  # Официальная должность в проекте - например, Java developer
    role = models.CharField(max_length=15, choices=role_choices)

    def __unicode__(self):
        return "(project=%s, participant=%s, role=%s)" % (self.project, self.participant, self.role)

projects/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.forms import ModelForm, Form
from projects import models
from projects.models import ProjectParticipant, Project, ProjectMilestone

__author__ = 'Ildar'


class ParticipantForm(forms.Form):
    project = forms.IntegerField(widget=forms.HiddenInput())
    # participant - instead of drop down list with all people make dynamically
    # loading list of people that reacts on user typing
    participant = forms.CharField(max_length=30, label="Person's username")
    appointment = forms.CharField(max_length=100, label="Position in project")
    role = forms.CharField(widget=forms.Select(choices=models.role_choices))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ParticipantForm, self).__init__(*args, **kwargs)

    def clean_project(self):
        project_id = self.cleaned_data['project']
        try:
            project = Project.objects.get(id=project_id)
        except Project.DoesNotExist:
            raise ValidationError("Project doesn't exist")
        if not project.team.filter(username=self.request.user.username).exists():
            raise ValidationError("You have no relationship to this project.")
        q1 = Q(project=project)
        q2 = Q(participant=self.request.user)
        participant = ProjectParticipant.objects.get(q1 & q2)
        if not participant.role == 'ADMIN':
            raise ValidationError("You're not administrator of this project.")

        return project_id

    def clean_participant(self):
        participant_username = self.cleaned_data['participant']
        try:
            user = User.objects.get(username=participant_username)
        except User.DoesNotExist:
            raise ValidationError("The specified user doesn't exist.")

        project_id = self.cleaned_data['project']
        if ProjectParticipant.objects.filter(project__id=project_id, participant=user).exists():
            # Данный юзер уже является частью команды данного проекта
            raise ValidationError("This user is already in this project's team.")

        return participant_username


class MilestoneForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        pk = kwargs.pop('pk', None)
        super(MilestoneForm, self).__init__(*args, **kwargs)
        project = Project.objects.get(id=pk)
        self.fields['responsible_people'].queryset = project.team

    class Meta:
        model = ProjectMilestone
        fields = ["project", "name", "description", "due_date", "responsible_people"]
        widgets = {
            'project': forms.HiddenInput(),
            'responsible_people': forms.SelectMultiple(),
            'due_date' : forms.TextInput(attrs={'type':'date'}),
        }


class LinkForm(Form):
    url = forms.URLField()
    description = forms.CharField(widget=forms.Textarea)

projects/templates/projects/add_link.html
{% extends 'project/layout.html' %}

{% block title %}Add link{% endblock %}

{% block content %}
    <h1>Add new link</h1>

    <form method="post" action="{% url 'projects:create_link' project_id %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Add" />
    </form>

    <script type="text/javascript">
        $(function() {
            $("#id_url").prop('required', 'required');
            $("#id_description").prop('required', 'required');
        });
    </script>
{% endblock %}

projects/templates/projects/add_milestone.html
{% extends 'project/layout.html' %}

{% block title %}Add milestone{% endblock %}

{% block content %}
    <h1>Add new milestone</h1>

    <form method="post" action="{% url 'projects:add_milestone' form.project.value %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Add" />
    </form>

    <script type="text/javascript">
        $(function() {
            $("#id_name").prop('required', 'required');
            $("#id_due_date").prop('required', 'required');
            $("#id_responsible_people").prop('required', 'required');
        });
    </script>
{% endblock %}

projects/templates/projects/add_person.html
{% extends 'project/layout.html' %}
{% load staticfiles %}

{% block title %}Add person{% endblock %}

{% block content %}
    <h1>Add new person to the project</h1>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <style>
        .ui-autocomplete {
            font-size: 14px;
        }
        .ui-autocomplete-loading {
            background: white url("{% static 'project/images/ui-anim_basic_16x16.gif' %}") right center no-repeat;
        }
    </style>
    <script type="text/javascript">
        $(function() {
            $("#id_participant").autocomplete({
                minLength: 3,
                source: "{% url 'projects:get_usernames' project.id %}"
            });
        })
    </script>

    <form method="post" action="{% url 'projects:add_person' form.project.value %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Add" />
    </form>

    <script type="text/javascript">
        $(function() {
            $("#id_participant").prop('required', 'required');
            $("#id_appointment").prop('required', 'required');
        });
    </script>
{% endblock %}

projects/templates/projects/create_project.html
{% extends 'project/layout.html' %}
{% load staticfiles %}

{% block title %}Create new project{% endblock %}

{% block content %}
    <h1>Create new project</h1>
    <span id="errSpan" style="visibility: hidden; color: red;">
        Work start date can't be greater than the work end date.
    </span>
    <form method="post" action="{% url 'projects:create_project' %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Create" />
    </form>

    <script type="text/javascript" src="{% static 'project/js/create_project.js' %}"></script>
{% endblock %}

projects/templates/projects/delete_project.html
{% extends 'project/layout.html' %}

{% block title %}Deleting project{% endblock %}

{% block content %}
    <h1>Delete project {{ project.name }}</h1>

    <form method="post" action="{% url 'projects:delete_project' project.id %}">
        {% csrf_token %}
        <span>
            Are you sure you want to delete this project?
            After this you can't have it back.
            All project's files and data will be deleted.
        </span>
        <input type="submit" value="Delete forever" />
    </form>
{% endblock %}

projects/templates/projects/edit_link.html
{% extends 'project/layout.html' %}

{% block title %}Edit link{% endblock %}

{% block content %}
    <h1>Edit link</h1>

    <form method="post" action="{% url 'projects:edit_link' link_id %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Save changes" />
    </form>
{% endblock %}

projects/templates/projects/edit_milestone.html
{% extends 'project/layout.html' %}

{% block title %}Edit milestone{% endblock %}

{% block content %}
    <h1>Edit milestone</h1>

    <form method="post" action="{% url 'projects:edit_milestone' milestone_id %}">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Save changes" />
    </form>
{% endblock %}

projects/templates/projects/not_admin.html
{% extends 'project/layout.html' %}

{% block title %}Operation restricted{% endblock %}

{% block content %}
    <h1>Operation access restricted</h1>
    <h3>You have no access to perform this operation since you're not an admin of this project.</h3>
{% endblock %}

projects/templates/projects/project_team.html
{% extends 'project/layout.html' %}
{% load staticfiles %}

{% block title %}Project Team{% endblock %}

{% block content %}
    <script type="text/javascript" src="{% static 'project/js/project_team.js' %}"></script>
    <script type="text/javascript">
        {% if not isAdmin %}
            $(function() {
                $("input[type=radio]").prop('disabled', true);
            });
        {% endif %}

        appointmentChangeUrl = "{% url 'projects:change_user_appointment' %}";
        csrfToken = "{{ csrf_token }}";
    </script>

    <form method="post" id="excludeUserForm"
          action="{% url 'projects:delete_person_from_project' project.id %}">
        {% csrf_token %}
        <input type="hidden" name="participant_id" id="participant_id" />
    </form>

    <h1>Project {{ project.name }} Team</h1>

    {% if error_msg %}
        <span style="color: red;">{{ error_msg }}</span><br />
    {% endif %}

    {% if isAdmin %}
        <a href="{% url 'projects:add_person' project.id %}">Add person to the project</a>
    {% endif %}

    <table class="rwd-table">
        <tr>
            <th>Participant</th>
            <th>Appointment</th>
            <th>Role</th>
            {% if isAdmin %}
                <th>Exclude</th>
            {% endif %}
        </tr>
        {% for participant in participants.all %}
            <tr>
                <td>
                    <a href="{% url 'users:view_profile' participant.participant.id %}">
                        {{ participant.participant.username }}
                    </a>
                </td>
                <td>
                    {% if isAdmin %}
                        <input type="text" value="{{ participant.appointment }}"
                               onblur="changeAppointment({{ participant.id }}, this)">
                    {% else %}
                        {{ participant.appointment }}
                    {% endif %}
                </td>
                <td>
                    {% for choice in role_choices %}
                        {% if participant.role == choice.0 %}
                            <input type="radio" name="role{{ participant.id }}"
                                   onclick="changeRole('{% url 'projects:change_user_role' participant.id %}', '{{ choice.0 }}')"
                                   id="choice{{ participant.participant.id }}{{ choice.0 }}" checked>{{ choice.1 }}
                        {% else %}
                            <input type="radio" name="role{{ participant.id }}"
                                   onclick="changeRole('{% url 'projects:change_user_role' participant.id %}', '{{ choice.0 }}')"
                                   id="choice{{ participant.participant.id }}{{ choice.0 }}">{{ choice.1 }}
                        {% endif %}
                        <!-- Restrict user admin changing his own role -->
                        {% if participant.participant.id == user.id %}
                            <script type="text/javascript">
                                $(function() {
                                    $("#choice" + "{{ participant.participant.id }}" + "{{ choice.0 }}")
                                            .prop('disabled', true);
                                });
                            </script>
                        {% endif %}
                    {% endfor %}
                </td>
                {% if isAdmin and user.id != participant.id %}
                <td>
                    <a href="javascript:excludeUser({{ participant.id }});">
                        Exclude user
                    </a>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

projects/templates/projects/restricted.html
{% extends 'project/layout.html' %}

{% block title %}Project restricted{% endblock %}

{% block content %}
    <h1>Project access restricted</h1>
    <h3>You have no access to this project.</h3>
{% endblock %}

projects/templates/projects/statistics.html
{% extends 'project/layout.html' %}

{% block title %}Application statistics{% endblock %}

{% block content %}
    <h1>Application Statistics</h1>

    <table>
        <tr>
            <td>Average count of tasks in your projects:</td>
            <td><b id="avg_val_proj">{{ avg_val_in_your_projects.0 }}</b></td>
        </tr>
        <tr>
            <td>Average count of tasks in entire application:</td>
            <td><b id="avg_val_app">{{ avg_val_in_all_projects.0 }}</b></td>
        </tr>
        <tr>
            <td>Projects started in the last 12 months:</td>
            <td>
                <ul>
                {% for mon in project_in_last_months %}
                    <li>{{ mon.0 }} - {{ mon.1 }} project{{ mon.1|pluralize }}</li>
                {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <td>Most popular positions in your projects:</td>
            <td>
                <ul>
                {% for pos in most_popular_appointments_in_your_projects %}
                    <li>{{ pos.0 }} - {{ pos.1 }} job{{ pos.1|pluralize }}</li>
                {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <td>Most popular positions in entire application:</td>
            <td>
            <ul>
            {% for pos in most_popular_appointment_in_app %}
                <li>{{ pos.0 }} - {{ pos.1 }} job{{ pos.1|pluralize }}</li>
            {% endfor %}
            </ul>
            </td>
        </tr>
    </table>

    <script type="text/javascript">
        $(function() {
            $("#avg_val_proj").html(parseFloat($("#avg_val_proj").html()).toFixed(2));
            $("#avg_val_app").html(parseFloat($("#avg_val_app").html()).toFixed(2));
        });
    </script>
{% endblock %}

projects/templates/projects/view_links.html
{% extends 'project/layout.html' %}

{% block title %}View project links{% endblock %}

{% block content %}
    <h1>Project {{ project.name }} links</h1>
    <a href="{% url 'projects:create_link' project.id %}">Create new link</a>
    {% if isAdmin %}
        <script type="text/javascript">
            function deleteLink(link_id) {
                var form = $("#deleteLinkForm");
                form.find("#link_id").val(link_id);
                form.submit();
            }
        </script>
        <form method="post" action="{% url 'projects:delete_link' %}" id="deleteLinkForm">
            {% csrf_token %}
            <input type="hidden" id="link_id" name="link_id" />
        </form>
    {% endif %}

    <table class="rwd-table">
        <tr>
            <th>URL</th>
            <th>Publisher</th>
            <th>Date of publishing</th>
            <th>More</th>
            {% if isAdmin %}
            <th>Delete</th>
            {% endif %}
        </tr>
        {% for link in project.projectlink_set.all %}
            <tr>
                <td><a href="{{ link.url }}">{{ link.url }}</a></td>
                <td><a href="{% url 'users:view_profile' link.publisher.id %}">
                    {{ link.publisher.username }}</a></td>
                <td>{{ link.publish_date|date }}</td>
                <td><a href="{% url 'projects:edit_link' link.id %}">More</a></td>
                {% if isAdmin %}
                <td><a href="javascript:deleteLink({{ link.id }});">Delete</a></td> <!-- Make it delete via JS -->
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}

projects/templates/projects/view_milestone.html
{% extends 'project/layout.html' %}

{% block title %}View milestone{% endblock %}

{% block content %}
    <h1>View milestone {{ milestone.name }}</h1>
    {% if isAdmin %}
    <script type="text/javascript">
        function deleteMilestone() {
            $("#deleteMilestoneForm").submit();
        }
    </script>
    <form method="post" id="deleteMilestoneForm" action="{% url 'projects:delete_milestone' milestone.id %}">
        {% csrf_token %}
    </form>
    <a href="javascript:deleteMilestone();">Delete milestone</a><br /> <!-- Activate on click the form above using JS -->
    <a href="{% url 'projects:edit_milestone' milestone.id %}">Edit milestone</a>
    <br /><br />
    {% endif %}

    <table>
        <tr>
            <td>Project:</td>
            <td><a href="{% url 'projects:view_project' milestone.project.id %}">
                {{ milestone.project.name }}</a></td>
        </tr>
        <tr>
            <td>Name:</td>
            <td>{{ milestone.name }}</td>
        </tr>
        <tr>
            <td>Description:</td>
            <td>{{ milestone.description }}</td>
        </tr>
        <tr>
            <td>Due date:</td>
            <td>{{ milestone.due_date|date }}</td>
        </tr>
        <tr>
            <td>Responsible people:</td>
            <td>
                <ul>
                    {% for person in milestone.responsible_people.all %}
                        <li>
                        <a href="{% url 'users:view_profile' person.id %}">{{ person.username }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
    </table>
{% endblock %}

projects/templates/projects/view_milestones.html
{% extends 'project/layout.html' %}

{% block title %}View milestones{% endblock %}

{% block content %}
    <h1>View project {{ project.name }} milestones</h1>
    <a href="{% url 'projects:add_milestone' project.id %}">Create new milestone</a>
    {% if project.projectmilestone_set.all %}
    <table class="rwd-table">
        <tr>
            <th>Name</th>
            <th>Due date</th>
            <th>More info</th>
        </tr>
            {% for milestone in project.projectmilestone_set.all %}
                <tr>
                    <td>{{ milestone.name }}</td>
                    <th>{{ milestone.due_date|date }}</th>
                    <td><a href="{% url 'projects:view_milestone' milestone.id %}">More info</a></td>
                </tr>
            {% endfor %}
    </table>
    {% else %}
        <br/><i>No milestones to display.</i>
    {% endif %}
{% endblock %}