PMApp/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'users.views.start_page', name='start_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^notifications/', include('user_notifications.urls', namespace='user_notifications')),
    # Вход в систему
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    # Операция выхода из системы
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
# coding=utf-8
from django.conf.urls import url
from projects import views

__author__ = 'Ildar'

urlpatterns = [
    # Главная страница проекта
    url(r'(?P<pk>\d+)/view/$', views.ViewProject.as_view(), name='view_project'),
    # Создать новый проект
    url(r'create/$', views.CreateProject.as_view(), name='create_project'),
    # Выбрать проект из списка для начала работы с ним
    url(r'choose/$', views.ChooseProject.as_view(), name='choose_project'),
    # Посмотреть команду проекта
    url(r'(?P<pk>\d+)/team/$', views.ProjectTeam.as_view(), name='project_team'),
    # Добавить нового сотрудника в команду проекта
    url(r'(?P<project_id>\d+)/add_person/$', views.AddPerson.as_view(), name='add_person'),
    # Вернуть юзернеймы пользователей, которые подходят под поисковую фразу
    url(r'(?P<project_id>\d+)/get_usernames/$', views.get_usernames, name='get_usernames'),
    # Удалить пользователя из проекта
    url(r'(?P<project_id>\d+)/team/delete/$', views.delete_person_from_project,
        name='delete_person_from_project'),
    # Сменить роль пользователя в проекте, роль может менять только админ проекта
    url(r'team/(?P<participant_id>\d+)/change_role/$', views.change_user_role,
        name='change_user_role'),
    # Сменить должность пользователя в проекте, должность может менять только админ проекта
    url(r'team/change_user_appointment/$', views.change_user_appointment, name='change_user_appointment'),
    # Удалить проект
    url(r'(?P<pk>\d+)/delete/$', views.DeleteProject.as_view(), name='delete_project'),
    # Добавить сообщение в чат
    url(r'(?P<project_id>\d+)/add_chat_message/$', views.add_chat_message, name='add_chat_message'),
    # Получить новые сообщения чата
    url(r'(?P<project_id>\d+)/get_chat_messages/$', views.get_chat_messages,
        name='get_chat_messages'),
    # Посмотреть промежуточные этапы данного проекта
    url(r'(?P<pk>\d+)/milestones/$', views.ViewMilestones.as_view(), name='view_milestones'),
    # Добавить новый промежуточный этап проекту
    url(r'(?P<pk>\d+)/add_milestone/$', views.AddMilestone.as_view(), name='add_milestone'),
    # Посмотреть отдельный промежуточный этап этого проекта
    url(r'milestones/(?P<pk>\d+)/view_milestone/$', views.ViewMilestone.as_view(), name='view_milestone'),
    # Редактировать промежуточный этап
    url(r'milestones/(?P<pk>\d+)/edit/$', views.EditMilestone.as_view(), name='edit_milestone'),
    # Удалить промежуточный этап
    url(r'milestones/(?P<milestone_id>\d+)/delete_milestone/$', views.delete_milestone, name='delete_milestone'),
    # Посмотреть ссылки, созданные для проекта
    url(r'(?P<pk>\d+)/links/view/$', views.ViewLinks.as_view(), name='view_links'),
    # Создать новую ссылку для проекта
    url(r'(?P<pk>\d+)/links/create_link/$', views.CreateLink.as_view(), name='create_link'),
    # Редактировать существующую ссылку
    url(r'links/(?P<pk>\d+)/edit_link/$', views.EditLink.as_view(), name='edit_link'),
    # Удалить ссылку
    url(r'links/delete_link/$', views.delete_link, name='delete_link'),

    # Статистика по сайту
    url(r'statistics/$', views.view_statistics, name='view_statistics'),
]

user_notifications/urls.py
# coding=utf-8
from django.conf.urls import url
from user_notifications import views

__author__ = 'Ildar'

urlpatterns = [
    # Посмотреть новые уведомления пользователя по всем проектам
    url(r'notifications/$', views.view_notifications, name='view_notifications'),
    # Подтвердить, что новые уведомления прочитаны юзером
    url(r'notifications_read/$', views.notifications_read, name='notifications_read'),
]

users/urls.py
# coding=utf-8
from django.conf.urls import url
from users import views

__author__ = 'Ildar'

urlpatterns = [
    # Регистрация нового пользователя
    url('registration/$', views.RegistrationView.as_view(), name='registration'),

    # Профиль стороннего пользователя
    url('(?P<pk>\d+)/view_profile/$', views.ViewUserProfile.as_view(), name='view_profile'),

    # Профиль пользователя
    url('profile/$', views.ProfileView.as_view(), name='profile'),
]

user_notifications/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models
from projects.models import ProjectDashboardNotification


class UserNotification(models.Model):
    """
    Уведомление юзера о событии в каком-либо проекте
    """
    notification = models.ForeignKey(ProjectDashboardNotification)
    user = models.ForeignKey(User)
    is_read = models.BooleanField()  # Прочитано ли уведомление юзером

    def __unicode__(self):
        return "(notification=%s, user=%s, is_read=%s)" % (self.notification, self.user, self.is_read)

user_notifications/forms.py
__author__ = 'Ildar'

user_notifications/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import render

# Create your views here.
from user_notifications.models import UserNotification
from django.db import connection


def view_notifications(request):
    unread_notifications = UserNotification.objects.filter(user=request.user, is_read=False)\
        .order_by('-notification__event_date')
    read_notifications = UserNotification.objects.filter(user=request.user, is_read=True)\
        .order_by('-notification__event_date')

    return render(request, 'user_notifications/user_notifications.html',
                  {'unread_notifs': unread_notifications, 'read_notifs': read_notifications})


def notifications_read(request):
    if request.method == "GET":
        raise Http404()

    # Set these notifications as read. Next time user will not see them as new.
    raw_sql = "update user_notifications_usernotification " \
              "set is_read = true " \
              "where user_id = %d" % request.user.id
    connection.cursor().execute(raw_sql)

    return JsonResponse({'success': True})

user_notifications/templates/user_notifications/user_notifications.html
{% extends 'project/layout.html' %}

{% block title %}User notifications{% endblock %}

{% block content %}
    <h1>Your notifications</h1>
    <script type="text/javascript">
        $(function() {
            $("#tabs").tabs();
        })
    </script>

    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Unread notifications</a></li>
            <li><a href="#tabs-2">Read notifications</a></li>
        </ul>

        <div id="tabs-1">
            {% if unread_notifs %}
            <table class="rwd-table">
                <tr>
                    <th>Project</th>
                    <th>Text</th>
                    <th>Event date</th>
                    <th>Event author</th>
                </tr>
                {% for notif in unread_notifs.all %}
                    <tr>
                        <td><a href="{% url 'projects:view_project' notif.notification.project.id %}">
                            {{ notif.notification.project.name }}
                        </a></td>
                        <td>{{ notif.notification.text }}</td>
                        <td>{{ notif.notification.event_date }}</td>
                        <td>
                            <a href="{% url 'users:view_profile' notif.notification.event_author.id %}">
                            {{ notif.notification.event_author }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <i>No new notifications.</i>
            {% endif %}
        </div>

        <div id="tabs-2">
            {% if read_notifs %}
            <table class="rwd-table">
                <tr>
                    <th>Project</th>
                    <th>Text</th>
                    <th>Event date</th>
                    <th>Event author</th>
                </tr>
                {% for notif in read_notifs.all %}
                    <tr>
                        <td><a href="{% url 'projects:view_project' notif.notification.project.id %}">
                            {{ notif.notification.project.name }}
                        </a></td>
                        <td>{{ notif.notification.text }}</td>
                        <td>{{ notif.notification.event_date }}</td>
                        <td>
                            <a href="{% url 'users:view_profile' notif.notification.event_author.id %}">
                            {{ notif.notification.event_author }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% else %}
                <i>No notifications yet.</i>
            {% endif %}
        </div>

    </div>

    <script type="text/javascript">
        $(function() {
            $.ajax({
                type: 'POST',
                url: "{% url 'user_notifications:notifications_read' %}",
                beforeSend: function(xhr) {
                    xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                }
            });
        });
    </script>
{% endblock %}