PMApp/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'users.views.start_page', name='start_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^tasks/', include('tasks.urls', namespace='tasks')),
    url(r'^notifications/', include('user_notifications.urls', namespace='user_notifications')),
    # Вход в систему
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    # Операция выхода из системы
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
# coding=utf-8
from django.conf.urls import url
from projects import views

__author__ = 'Ildar'

urlpatterns = [
    # Главная страница проекта
    url(r'(?P<pk>\d+)/view/$', views.ViewProject.as_view(), name='view_project'),
    # Создать новый проект
    url(r'create/$', views.CreateProject.as_view(), name='create_project'),
    # Выбрать проект из списка для начала работы с ним
    url(r'choose/$', views.ChooseProject.as_view(), name='choose_project'),
    # Посмотреть команду проекта
    url(r'(?P<pk>\d+)/team/$', views.ProjectTeam.as_view(), name='project_team'),
    # Добавить нового сотрудника в команду проекта
    url(r'(?P<project_id>\d+)/add_person/$', views.AddPerson.as_view(), name='add_person'),
    # Вернуть юзернеймы пользователей, которые подходят под поисковую фразу
    url(r'(?P<project_id>\d+)/get_usernames/$', views.get_usernames, name='get_usernames'),
    # Удалить пользователя из проекта
    url(r'(?P<project_id>\d+)/team/delete/$', views.delete_person_from_project,
        name='delete_person_from_project'),
    # Сменить роль пользователя в проекте, роль может менять только админ проекта
    url(r'team/(?P<participant_id>\d+)/change_role/$', views.change_user_role,
        name='change_user_role'),
    # Сменить должность пользователя в проекте, должность может менять только админ проекта
    url(r'team/change_user_appointment/$', views.change_user_appointment, name='change_user_appointment'),
    # Удалить проект
    url(r'(?P<pk>\d+)/delete/$', views.DeleteProject.as_view(), name='delete_project'),
    # Добавить сообщение в чат
    url(r'(?P<project_id>\d+)/add_chat_message/$', views.add_chat_message, name='add_chat_message'),
    # Получить новые сообщения чата
    url(r'(?P<project_id>\d+)/get_chat_messages/$', views.get_chat_messages,
        name='get_chat_messages'),
    # Посмотреть промежуточные этапы данного проекта
    url(r'(?P<pk>\d+)/milestones/$', views.ViewMilestones.as_view(), name='view_milestones'),
    # Добавить новый промежуточный этап проекту
    url(r'(?P<pk>\d+)/add_milestone/$', views.AddMilestone.as_view(), name='add_milestone'),
    # Посмотреть отдельный промежуточный этап этого проекта
    url(r'milestones/(?P<pk>\d+)/view_milestone/$', views.ViewMilestone.as_view(), name='view_milestone'),
    # Редактировать промежуточный этап
    url(r'milestones/(?P<pk>\d+)/edit/$', views.EditMilestone.as_view(), name='edit_milestone'),
    # Удалить промежуточный этап
    url(r'milestones/(?P<milestone_id>\d+)/delete_milestone/$', views.delete_milestone, name='delete_milestone'),
    # Посмотреть ссылки, созданные для проекта
    url(r'(?P<pk>\d+)/links/view/$', views.ViewLinks.as_view(), name='view_links'),
    # Создать новую ссылку для проекта
    url(r'(?P<pk>\d+)/links/create_link/$', views.CreateLink.as_view(), name='create_link'),
    # Редактировать существующую ссылку
    url(r'links/(?P<pk>\d+)/edit_link/$', views.EditLink.as_view(), name='edit_link'),
    # Удалить ссылку
    url(r'links/delete_link/$', views.delete_link, name='delete_link'),

    # Статистика по сайту
    url(r'statistics/$', views.view_statistics, name='view_statistics'),
]

tasks/urls.py
# coding=utf-8
from django.conf.urls import url
from tasks import views

__author__ = 'Ildar'

urlpatterns = [
    # Посмотреть все таски данного проекта
    url(r'view/(?P<project_id>\d+)/$', views.view_project_tasks, name='view_project_tasks'),
    # Добавить новый таск в проект
    url(r'add/(?P<project_id>\d+)/$', views.add_task_to_project, name='add_task_to_project'),
    # Посмотреть все "короткие" (меньше 7 дней) таски проекта
    url(r'/short_tasks/(?P<project_id>\d+)/$', views.view_short_tasks, name='view_short_tasks'),
    # Посмотреть детали отдельного таска
    url(r'(?P<pk>\d+)/view/$', views.ViewTask.as_view(), name='view_task'),
    # Редактировать таск
    url(r'(?P<pk>\d+)/edit/$', views.EditTask.as_view(), name='edit_task'),
    # Закрыть таск
    url(r'(?P<task_id>\d+)/close_task/$', views.close_task, name='close_task'),
    # Удалить таск
    url(r'(?P<task_id>\d+)/delete/$', views.delete_task, name='delete_task'),
    # Добавить файл таску
    url(r'(?P<task_id>\d+)/add_file/$', views.add_file_to_task, name='add_file_to_task'),
    # Загрузить файл
    url(r'download_file/(?P<file_id>\d+)/$', views.download_file, name='download_file'),
    # Удалить файл таска
    url(r'files/(?P<file_id>\d+)/remove/$', views.remove_task_file, name='remove_task_file'),
]

users/urls.py
# coding=utf-8
from django.conf.urls import url
from users import views

__author__ = 'Ildar'

urlpatterns = [
    # Регистрация нового пользователя
    url('registration/$', views.RegistrationView.as_view(), name='registration'),

    # Профиль стороннего пользователя
    url('(?P<pk>\d+)/view_profile/$', views.ViewUserProfile.as_view(), name='view_profile'),

    # Профиль пользователя
    url('profile/$', views.ProfileView.as_view(), name='profile'),
]

projects/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Project(models.Model):
    """ Проект
    """
    name = models.CharField(max_length=150)  # Название проекта
    description = models.TextField(max_length=1000, null=True, blank=True)  # Описание
    work_start = models.DateField()  # Дата начала работы над проектом
    work_deadline = models.DateField()  # Дата окончания работы над проектом

    team = models.ManyToManyField(User,
                                  through='ProjectParticipant')  # Команда, работающая над проектом - список юзеров

    def __unicode__(self):
        return "(id=%d, name=%s)" % (self.id, self.name)


class ProjectDashboardNotification(models.Model):
    """
    Уведомления о каком-либо действии с проектом на главной странице проекта
    """
    project = models.ForeignKey(Project)  # Проект, в котором произошло действие
    text = models.CharField(max_length=250)  # Текст уведомления
    event_date = models.DateTimeField()  # Дата, когда событие произошло
    event_author = models.ForeignKey(User)  # Кто совершил действие, отраженное в данном уведомлении

    def __unicode__(self):
        return "(project=%s, author=%s, date=%s)" % (
            self.project, self.event_author, self.event_date)


class ProjectChatMessage(models.Model):
    """
    Сообщение в чате проекта
    """
    project = models.ForeignKey(Project)
    author = models.ForeignKey(User)  # Автор сообщения
    text = models.CharField(max_length=200)  # Текст сообщения
    publish_date = models.DateTimeField()  # Дата публикации сообщения в чате

    def __unicode__(self):
        return "(project=%s, author=%s, text=(%s), publish_date=%s)" \
               % (self.project, self.author,
                  self.text if len(self.text.__str__()) < 50 else (self.text[:50] + "..."),
                  self.publish_date)


class ProjectLink(models.Model):
    """
    Ссылка на какой-то сторонний ресурс, связанный с проектом, например, исходный код приложения проекта
    """
    project = models.ForeignKey(Project)
    url = models.URLField()
    description = models.TextField()
    publisher = models.ForeignKey(User)  # Кто разместил ссылку
    publish_date = models.DateTimeField()  # Дата публикации ссылки

    def __unicode__(self):
        return "(project=%s, url=%s)" % (self.project, self.url)


class ProjectMilestone(models.Model):
    """
    Промежуточный этап разработки проекта
    """
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    due_date = models.DateField()  # К какому числу этап должен быть готов
    responsible_people = models.ManyToManyField(User)  # Кто ответственнен за достижение этапа

    def __unicode__(self):
        return "(project=%s, name=%s, due date=%s)" % (self.project, self.name, self.due_date)


role_choices = (  # Роль(привилегии) в проекте
             ("ADMIN", "Administrator"),
             ("USER", "Teammate"),
          )


class ProjectParticipant(models.Model):
    """
    Участник проекта
    """
    project = models.ForeignKey(Project)
    participant = models.ForeignKey(User)
    appointment = models.CharField(max_length=100)  # Официальная должность в проекте - например, Java developer
    role = models.CharField(max_length=15, choices=role_choices)

    def __unicode__(self):
        return "(project=%s, participant=%s, role=%s)" % (self.project, self.participant, self.role)

projects/forms.py
# coding=utf-8
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.forms import ModelForm, Form
from projects import models
from projects.models import ProjectParticipant, Project, ProjectMilestone

__author__ = 'Ildar'


class ParticipantForm(forms.Form):
    project = forms.IntegerField(widget=forms.HiddenInput())
    # participant - instead of drop down list with all people make dynamically
    # loading list of people that reacts on user typing
    participant = forms.CharField(max_length=30, label="Person's username")
    appointment = forms.CharField(max_length=100, label="Position in project")
    role = forms.CharField(widget=forms.Select(choices=models.role_choices))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ParticipantForm, self).__init__(*args, **kwargs)

    def clean_project(self):
        project_id = self.cleaned_data['project']
        try:
            project = Project.objects.get(id=project_id)
        except Project.DoesNotExist:
            raise ValidationError("Project doesn't exist")
        if not project.team.filter(username=self.request.user.username).exists():
            raise ValidationError("You have no relationship to this project.")
        q1 = Q(project=project)
        q2 = Q(participant=self.request.user)
        participant = ProjectParticipant.objects.get(q1 & q2)
        if not participant.role == 'ADMIN':
            raise ValidationError("You're not administrator of this project.")

        return project_id

    def clean_participant(self):
        participant_username = self.cleaned_data['participant']
        try:
            user = User.objects.get(username=participant_username)
        except User.DoesNotExist:
            raise ValidationError("The specified user doesn't exist.")

        project_id = self.cleaned_data['project']
        if ProjectParticipant.objects.filter(project__id=project_id, participant=user).exists():
            # Данный юзер уже является частью команды данного проекта
            raise ValidationError("This user is already in this project's team.")

        return participant_username


class MilestoneForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        pk = kwargs.pop('pk', None)
        super(MilestoneForm, self).__init__(*args, **kwargs)
        project = Project.objects.get(id=pk)
        self.fields['responsible_people'].queryset = project.team

    class Meta:
        model = ProjectMilestone
        fields = ["project", "name", "description", "due_date", "responsible_people"]
        widgets = {
            'project': forms.HiddenInput(),
            'responsible_people': forms.SelectMultiple(),
            'due_date' : forms.TextInput(attrs={'type':'date'}),
        }


class LinkForm(Form):
    url = forms.URLField()
    description = forms.CharField(widget=forms.Textarea)

templates/project/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Layout page{% endblock %}</title>
    <script type="text/javascript" src="{% static 'project/jquery/jquery.min.js' %}"></script>
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'project/css/styles.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'project/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'project/css/style.css' %}">
</head>
<body>

    <div id="header">
        <span id="app-name">
            <a class="head-link" href="{% url 'start_page' %}">
                {% if project %}
                PMApp - <span title="{{ project.description }}">{{ project.name }}</span>
                {% else %}
                PMApp
                {% endif %}
            </a>
        </span>
        <div id="menu">
            {% if user.is_anonymous %}
                <a href="{% url 'login' %}">Log In</a>
                <a href="{% url 'users:registration' %}">Register</a>
            {% else %}
                {% if project %}
                    <a href="{% url 'tasks:view_project_tasks' project.id %}">Tasks</a>
                    <a href="{% url 'projects:project_team' project.id %}">Team</a>
                    <a href="{% url 'projects:view_milestones' project.id %}" style="margin-right: 4px;">
                        Milestones ({{ project.projectmilestone_set.count }})
                    </a>
                    <a href="{% url 'projects:view_links' project.id %}" style="margin-right: 4px;">
                        Links ({{ project.projectlink_set.count }})
                    </a>
                    <a href="{% url 'projects:view_project' project.id %}">Dashboard</a>
                {% else %}
                    <a href="{% url 'projects:view_statistics' %}">Statistics</a>
                    <a href="{% url 'projects:create_project' %}">Create project</a>
                {% endif %}
                <a href="{% url 'projects:choose_project' %}">Choose project</a>
                <a href="{% url 'users:profile' %}">{{ user }}</a>
                <a href="{% url 'logout' %}?next=/">Logout</a>
            {% endif %}
        </div>
    </div>

    <div id="{{ project|yesno:"page," }}">
        <div id="{{ project|yesno:"content,content_notfloat" }}">
            {% block content %}
                Content of application
            {% endblock %}
        </div>

        {% if project %}
            <div id="left-side">
                <h4>The Team</h4>
                <table style="border: 1px solid black;">
                    {% for teammate in project.projectparticipant_set.all %}
                        <tr>
                            <td>
                            {% if teammate.role == 'ADMIN' %}
                                <img src="{% static 'project/images/admin.png' %}" title="Administrator">
                            {% endif %}
                            </td>
                            <td>
                            <a href="{% url 'users:view_profile' teammate.participant.id %}">
                                {{ teammate.participant.username }}</a>
                            </td>
                            <td>
                             - {{ teammate.appointment }}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <h4>Timeline</h4>
                From {{ project.work_start }} till {{ project.work_deadline }}
            </div>
            <div id="clearingDiv"></div>

            <script type="text/javascript" src="{% static "project/jquery/jquery.ui.chatbox.js" %}"></script>
            <link rel="stylesheet" href="{% static "project/jquery/jquery.ui.chatbox.css" %}">
            <script type="text/javascript" src="{% static "project/js/chat.js" %}"></script>
            <script type="text/javascript">
                var user = "{{ user }}";
                var token = "{{ csrf_token }}";
                var getChatMessagesUrl = "{% url 'projects:get_chat_messages' project.id %}";
                var addChatMessageUrl = "{% url 'projects:add_chat_message' project.id %}";
            </script>
            <div id="chatBox"></div>
        {% endif %}
    </div>

    <div id="footer">
        Copyright&copy; 2015, Ildar&reg;
    </div>
</body>
</html>

templates/project/start_page.html
{% extends 'project/layout.html' %}

{% block title %}PMApp Start Page{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
    <h3>This project management application allows you to keep track of your own projects for free!</h3>
    <h3>To start, please <a href="{% url 'login' %}">log in</a>
        or <a href="{% url 'users:registration' %}">register</a>.</h3>
{% endblock %}